### ISSUE TITLE
Ethereum A1 test network tap can not receive test coins

### ISSUE THREAD

**Issue by Lxx982368** [taikoxyz/taiko-client#112]
Ethereum A1 test network tap can not receive test coins

**Comment by davidtaikocha** [comment]
Its because the Twitter API is hitting a rate limit. Because of this, we can't recognize the Ethereum address in your tweet. Next steps: You will need to wait and try again. If you continue having problems, you can also send your address in our Discord's "🪙︱manual-faucet" channel and ask the community to send you testnet funds.
