### ISSUE TITLE
A normal prover should at least wait `protocolConfig.targetProofTime` seconds before submitting proofs

### ISSUE THREAD

**Issue by davidtaikocha** [taikoxyz/taiko-client#231]

**Comment by Brechtpd** [comment]
Targeting a fixed proof target time probably not very stable, because that would mean the base fee would change regardless of what the proof reward is. Calculating the proof delay based on the expected reward the proof would get when it ends up onchain seems like a more stable way to handle this. The expected prover reward would be something the prover could set personally to whatever value it wants.

**Comment by davidtaikocha** [comment]
> Targeting a fixed proof target time probably not very stable, because that would mean the base fee would change regardless of what the proof reward is. Calculating the proof delay based on the expected reward the proof would get when it ends up onchain seems like a more stable way to handle this. The expected prover reward would be something the prover could set personally to whatever value it wants.

agreed, maybe we can change the current codebase to do that? cc @RogerLamTd
